### ISSUE TITLE
[bug] cv link broken

### ISSUE THREAD

**Issue by mcsitter** [CriticalNameError/dammrath.tech#1]
Reproduce this issue by going to [dammrath.tech](https://dammrath.tech) and click on `Download Resume`.

What should happen is that the html links to [https://dammrath.tech/cv.pdf](https://dammrath.tech/cv.pdf) and the pdf is opened, i would suggest in a new tab.

What actually happens is that the link is broken and a 404 page is shown instead.

**Comment by CriticalNameError** [comment]
gefixt in master
https://github.com/CriticalNameError/dammrath.tech/commit/699dd4db1655f2525e3e1571fe8a186e0cbe4fd5
